# Generated by Django 6.0.2 on 2026-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(blank=True, max_length=50, null=True)),
                ('courses', models.CharField(blank=True, max_length=50, null=True)),
                ('teachers', models.CharField(blank=True, max_length=50, null=True)),
                ('satisfaction', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
