# Generated by Django 6.0.2 on 2026-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'درباره', 'verbose_name_plural': 'بخش درباره'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام تماس', 'verbose_name_plural': 'پیام\u200cهای تماس'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'بخش هدر', 'verbose_name_plural': 'بخش هدر سایت'},
        ),
        migrations.AlterModelOptions(
            name='placementtestsubmission',
            options={'verbose_name': 'تست تعیین سطح', 'verbose_name_plural': 'تست\u200cهای تعیین سطح'},
        ),
        migrations.AlterModelOptions(
            name='sitestats',
            options={'verbose_name': 'آمار سایت', 'verbose_name_plural': 'آمار سایت'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'نظر دانش\u200cآموز', 'verbose_name_plural': 'نظرات دانش\u200cآموزان'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='about',
            name='founded_year',
            field=models.CharField(max_length=50, verbose_name='سال تأسیس'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100, verbose_name='سطح دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان دوره'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر پس\u200cزمینه'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title_highlight',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن برجسته'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title_line1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='خط اول عنوان'),
        ),
        migrations.AlterField(
            model_name='placementtestsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='placementtestsubmission',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='placementtestsubmission',
            name='level_result',
            field=models.CharField(max_length=50, verbose_name='نتیجه سطح'),
        ),
        migrations.AlterField(
            model_name='placementtestsubmission',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='placementtestsubmission',
            name='score',
            field=models.IntegerField(verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='courses',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='satisfaction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رضایت'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='students',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دانش\u200cآموزان'),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='teachers',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اساتید'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(max_length=100, verbose_name='کلاس آیکن'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام شبکه'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(verbose_name='سال تجربه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='expertise',
            field=models.CharField(max_length=200, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال باشد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(max_length=200, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(verbose_name='متن نظر'),
        ),
    ]
