# Generated by Django 6.0.2 on 2026-02-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.CharField(default='موبایل + دسکتاپ', max_length=200, verbose_name='دسترسی'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=True, verbose_name='گواهینامه دارد'),
        ),
        migrations.AddField(
            model_name='course',
            name='test_duration',
            field=models.CharField(blank=True, help_text='مثلاً 10 ساعت', max_length=100, verbose_name='مدت زمان آزمون'),
        ),
        migrations.AddField(
            model_name='course',
            name='test_level',
            field=models.CharField(blank=True, help_text='مثلاً A1/A2 یا آسان/متوسط', max_length=100, verbose_name='سطح تست دوره'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='زبان تدریس'),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='خروجی یادگیری')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='core.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'خروجی یادگیری',
                'verbose_name_plural': 'خروجی\u200cهای یادگیری',
            },
        ),
    ]
