# Generated by Django 6.0.2 on 2026-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_access_course_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='placement_pass_percent',
            field=models.PositiveSmallIntegerField(default=85, help_text='اگر کاربر این درصد یا بیشتر بزند مجاز است', verbose_name='درصد قبولی تست'),
        ),
    ]
