# Generated by Django 6.0.2 on 2026-02-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_placement_pass_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='placement_pass_percent',
        ),
    ]
