# Generated by Django 6.0.2 on 2026-04-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_course_placement_pass_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
