# Generated by Django 6.0.2 on 2026-04-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacementTestSubmission',
        ),
    ]
