# Generated by Django 6.0.2 on 2026-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_placementtestsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='شماره تلفن'),
        ),
    ]
