# Generated by Django 6.0.2 on 2026-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='اختیاری - در صورت خالی بودن از روی لینک تشخیص داده می\u200cشود', max_length=100, verbose_name='کلاس آیکن'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(blank=True, help_text='اختیاری - در صورت خالی بودن از روی لینک تشخیص داده می\u200cشود', max_length=100, verbose_name='نام شبکه'),
        ),
    ]
