# Generated by Django 6.0.2 on 2026-02-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], max_length=2, verbose_name='سطح سوال')),
                ('explanation', models.TextField(blank=True, verbose_name='توضیح پس از پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال تعیین سطح',
                'verbose_name_plural': 'سوالات تعیین سطح',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دانش\u200cآموز')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], max_length=2, verbose_name='سطح تشخیص داده شده')),
                ('score', models.PositiveIntegerField(verbose_name='تعداد پاسخ صحیح')),
                ('total', models.PositiveIntegerField(verbose_name='تعداد کل سوالات')),
                ('time_seconds', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (ثانیه)')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آزمون')),
            ],
            options={
                'verbose_name': 'نتیجه تست',
                'verbose_name_plural': 'نتایج تست\u200cها',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='placement.placementquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
            },
        ),
    ]
