# Generated by Django 6.0.2 on 2026-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration_minutes', models.PositiveIntegerField(default=10, verbose_name='مدت زمان کل آزمون (دقیقه)')),
            ],
            options={
                'verbose_name': 'تنظیمات تست تعیین سطح',
                'verbose_name_plural': 'تنظیمات تست تعیین سطح',
            },
        ),
    ]
