# Generated by Django 6.0.2 on 2026-02-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_placement_pass_percent'),
        ('placement', '0002_placementtestsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='course',
            field=models.ForeignKey(blank=True, help_text='در صورت خالی بودن سوال در تست عمومی نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_questions', to='core.course', verbose_name='دوره'),
        ),
    ]
