# Generated by Django 6.0.2 on 2026-02-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementquestion_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementquestion',
            name='course',
        ),
    ]
