# Generated by Django 6.0.2 on 2026-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_placementquestion_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementresult',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
