# Generated by Django 6.0.2 on 2026-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_placementresult_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementresult',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='شماره تلفن'),
        ),
    ]
