# Generated by Django 6.0.2 on 2026-04-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_alter_placementresult_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementresult',
            name='email',
        ),
    ]
